# Generated by Django 4.2.2 on 2023-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Mugs', 'Mugs')], max_length=50),
        ),
    ]
