# Generated by Django 4.2.2 on 2023-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Mugs', 'Mugs')], max_length=50, unique=True),
        ),
    ]
