# Generated by Django 4.2.2 on 2023-07-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoppingcartsession_shoppingcartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartsession',
            old_name='cart_id',
            new_name='cart_uuid',
        ),
    ]
